### ISSUE TITLE
TypeError: Must provide Source. Received: {}

### ISSUE THREAD

**Issue by fvisticot** [micimize/graphql-to-dart#3]
How to fixe this issue ?

**Comment by micimize** [comment]
This is probably because I still haven't updated to the latest codegen api (#2)

You can try with `"graphql-code-generator": "^0.12.6"`, but it is still very experimental

**Comment by micimize** [comment]
Version `0.1.0-alpha1` should now work with `graphql-code-generator@0.18.0`

**Comment by fvisticot** [comment]
I have tested with the following package.json
```
{
  "devDependencies": {
    "graphql": "^14.1.1",
    "graphql-code-generator": "^0.18.0",
    "graphql-codegen-typescript-common": "^0.17.0",
    "graphql-codegen-typescript-server": "^0.17.0",
    "graphql-to-dart": "0.1.0-alpha1"
  }
}
```


and get this error:

```
.bin/gql-gen
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate lib/serializers/graphql.dart
      ✖ Load GraphQL schemas
        → Must provide Source. Received: {}
        Load GraphQL documents
        Generate


  Found 1 error

   ✖ lib/serializers/graphql.dart
    TypeError: Must provide Source. Received: {}


Something went wrong
error Command failed with exit code 1.
```

**Comment by micimize** [comment]
sorry, try with `0.1.0-alpha3`. `npm publish` doesn't seem to include `dist/` be default anymore 😅

**Comment by fvisticot** [comment]
unfortunately i get exactly the same issue :( . Did you try by yourself ? can you add a test with a yaml to check that it is working ?

**Comment by micimize** [comment]
I did - found one issue while testing different configs and published fix as `0.1.1-alpha`, but it doesn't look like the same issue. I was able to generate output with just
```yaml
schema: "./schema/__generated__/schema.json"
documents: 
- "./lib/gql/raw/recordFragments.gql"
- "./lib/gql/raw/metricFragments.gql"
- "./lib/gql/raw/eventFragments.gql"
- "./lib/gql/raw/GetSchedule.gql"
- "./lib/gql/raw/GetFreeforms.gql"
- "./lib/gql/raw/GetUserEventRecords.gql"
- "./lib/gql/raw/GetUserMetrics.gql"
- "./lib/gql/raw/UpsertEventRecord.gql"
- "./lib/gql/raw/UpsertEvent.gql"
overwrite: true
generates:
  lib/serializers/graphql.dart:
    plugins:
      - graphql-to-dart
```

**Comment by fvisticot** [comment]
It is OK now with the following codegen.yml file

With the following configuration a dart file is generated.
Now I get the issue with scalar type (I18n).
Can you please advice how to add Scalar feature in codegen.yml file ?

```
schema: "<url_gate>/graphql"
documents: 
overwrite: true
generates:
  lib/serializers/graphql.dart:
    plugins:
      - graphql-to-dart
```
