### ISSUE TITLE
Override schema types of specific fields with custom scalars

### ISSUE THREAD

**Issue by fvisticot** [micimize/graphql-to-dart#7]
By example, the Schema I'm using is not managing date field properly and those date field are managed as String.
I would like to overload type of some fields with configuration.

By Exemple:
From Schema:
creationDate String 

I would like to transform to
creationDate DateTime

**Comment by micimize** [comment]
Not possible to do exactly that right now, but you could use the conditional mixin config to do something similar:
```yaml
  mixins:
  # add the mixin {{name}} when the given fields are found in a model
  - when:
      fields:
      - creationDate
    name: FixDate
```
where `FixDate` is something like
```dart
class FixDate {
  String creationDate;
  DateTime get created => DateTime.parse(creationDate).toLocal();
  set created(DateTime date) => creationDate = date.toUtc().toIso8601String();
}
```

**Comment by fvisticot** [comment]
> Not possible to do exactly that right now, but you could use the conditional mixin config to do something similar:
> 
> ```yaml
>   mixins:
>   # add the mixin {{name}} when the given fields are found in a model
>   - when:
>       fields:
>       - creationDate
>     name: FixDate
> ```
> 
> where `FixDate` is something like
> 
> ```dart
> class Entity {
>   String creationDate;
>   get creationDateFix => dateFromJson(creationDate);
> }
> ```

Sorry to disturb you again and big tx for your support

- Do I have to create an Entity class or FixDate class ?
- How to specify the new DateTime dart target class for my creationDate field ?
- Where do I need to place this class ? / Any sample code ?

**Comment by micimize** [comment]
sorry, `Entity` was a typo, should be `FixDate`. So, you can add a `./base.dart` to `parts` and place it there, next to your `generates` target. So, if you're generating `lib/serializers/graphql.dart`, this should work:
```dart
// in lib/serializers/base.dart
class FixDate {
  String creationDate;
  
  DateTime get created => DateTime.parse(creationDate).toLocal();

  set created(DateTime date) => creationDate = date.toUtc().toIso8601String();
}
```
Config section of `codegen.yml`:
```yaml
config:
  mixins:
  # add the mixin {{name}} when the given fields are found in a model
  - when:
      fields:
      - creationDate
    name: FixDate
  parts:
  - "./base.dart"
  - "./graphql.g.dart" 
```
